# Generated by Django 4.2.1 on 2023-06-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bgimage',
            field=models.ImageField(default='/profile/Default.jpg', upload_to='profileImage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile/Default.jpg', upload_to='profileImage'),
        ),
    ]
