# Generated by Django 4.2.1 on 2023-06-07 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_user_fname_user_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bgimage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
