# Generated by Django 4.2.1 on 2023-06-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_profile_bgimage_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bgimage',
            field=models.ImageField(default='/profile/bgImage.jpg', upload_to='profileBanner'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile/Default.jpg', upload_to='profileImage'),
        ),
    ]
