# Generated by Django 4.2.1 on 2023-06-09 00:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_profile_bgimage_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bgimage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profileBanner'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profileImage'),
        ),
    ]
